import Head from "next/head"

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="h-screen bg-gradient-to-r from-cyan-500 to-blue-500 flex items-center justify-center">
                <div className="bg-neutral-200 rounded-lg w-[500px] h-[500px] shadow-md hover:shadow-lg p-4 transition-all">
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed enim excepturi
                    doloribus at quo aliquam dolorem aspernatur, unde tempora eius numquam nihil
                    facere. Voluptates, ipsum sapiente odio dicta eligendi illum!
                </div>
            </main>
        </div>
    )
}
