import Head from "next/head"
import Header from "../components/Header"
import LotteryEntrance from "../components/LotteryEntrance"

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="h-screen bg-gradient-to-r from-cyan-500 to-blue-500 flex items-start flex-col">
                <Header />
                <div className="flex items-center justify-center w-full h-full">
                    <div className="bg-neutral-100 rounded-lg w-[500px] h-[500px] shadow-md hover:shadow-lg p-4 transition-all flex items-center justify-center">
                        <LotteryEntrance />
                    </div>
                </div>
            </main>
        </div>
    )
}
